### ISSUE TITLE
What is the status of this repo?

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/workshops#1]
Is it still WIP or can it be archived?

**Comment by bnjmnsbl** [comment]
this repo was used by christian h. (via @julizet ) for a workshop last year. there *might* be more workshops in the future...i guess

**Comment by ff6347** [comment]
@julizet what is the status?

**Comment by julizet** [comment]
This repo belongs to Chrisitan H.
I once used it on the behalf of "Offene Werkstatt" but unfortunately this lead to a conflict with Christian as he is the owner of the repo and was not amused by any re-structuring of folders etc. 

That's why Sara and me created this [Repo](https://github.com/technologiestiftung/werkstatt)
